# Generated by Django 4.0.3 on 2022-03-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='cover',
            field=models.ImageField(blank=True, upload_to='covers/'),
        ),
        migrations.AddField(
            model_name='items',
            name='description',
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='items',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='items',
            name='published',
            field=models.DateField(auto_now=True),
        ),
    ]
