# Generated by Django 4.0.3 on 2022-03-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_items_cover_items_description_items_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='published',
            field=models.DateField(auto_now_add=True),
        ),
    ]
