# Generated by Django 4.0.3 on 2022-03-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_alter_items_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
