# Generated by Django 4.0.3 on 2022-03-20 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_alter_items_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_10', models.CharField(blank=True, max_length=10)),
                ('number_13', models.CharField(blank=True, max_length=13)),
            ],
        ),
        migrations.AddField(
            model_name='items',
            name='number',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.itemnumber'),
        ),
    ]
