# Generated by Django 4.0.3 on 2022-03-20 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_itemnumber_items_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.items')),
            ],
        ),
    ]
