# Generated by Django 4.0.3 on 2022-03-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0008_alter_author_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
